wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709895029.429268
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      3:
      - 23
      4: 3.11.8
      5: 0.16.3
      6: 4.38.1
      8:
      - 1
      - 5
      13: linux-x86_64
